# Generated by Django 3.2 on 2021-05-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('total_notices', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('charge', models.TextField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notices.country')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notices.notice')),
            ],
            options={
                'db_table': 'nationality',
            },
        ),
    ]
